version: '3.1'

services:

  db:
    image: mariadb:10.6.10
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: allane_se_demo
    ports:
      - 3306:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 18080:8080